/// Generated by https://quicktype.io

export interface AllMusicsOfSpotify {
    tracks: Track[];
    limit:  number;
    offset: number;
    total:  number;
    msg:    string;
}

export interface Track {
    album:             string;
    artist_names:      string[];
    duration_ms:       number;
    id:                string;
    image_preview_max: string;
    image_preview_min: string;
    track_name:        string;
    url_track:         string;
}
