// Generated by https://quicktype.io

export interface AllUsers {
    users:  Users[];
    length: number;
}

export interface Users {
    id:        string;
    user_name: string;
    email:     string;
}
