// Generated by https://quicktype.io

export interface ResponseSearchTrack {
    tracks: Track[];
    total:  number;
}

export interface Track {
    album:             string;
    artist_names:      string;
    duration_ms:       number;
    id:                string;
    image_preview_max: string;
    image_preview_min: string;
    track_name:        string;
    url_track:         string;
}
