// Generated by https://quicktype.io

export interface DataDBOfUser {
    newTracks: NewTrack[];
    number:    number;
    limit:     number;
    offset:    number;
    msg:       string;
}

export interface NewTrack {
    album:             string;
    artist_names:      string[];
    duration_ms:       number;
    id:                string;
    image_preview_max: string;
    image_preview_min: string;
    track_name:        string;
    url_track:         string;
    music_api_id:      string
}
