// Generated by https://quicktype.io

export interface SuccesfulPost {
    song: dataBaseSong;
    msg:  string;
}

export interface dataBaseSong {
    id:                string;
    track_name:        string;
    artist_names:      string;
    album:             string;
    url_track:         string;
    duration_ms:       number;
    image_preview_max: string;
    image_preview_min: string;
    user_id:           UserID;
}

export interface UserID {
    id:        string;
    user_name: string;
    email:     string;
}
