// Generated by https://quicktype.io

export interface UserLogged {
    user: User
}

export interface User {
    id:       string;
    userName: string;
    email:    string;
}

export interface NotLogged {
    msg:string
}